<?php

namespace Database\Seeders;

use App\Models\PromotionRule;
use Illuminate\Database\Seeder;

class PromotionRuleSeeder extends Seeder
{
    public function run(): void
    {
        $rules = [
            [
                'education_level' => 'primaria',
                'grade_number' => 1,
                'rule_name' => 'Promoción guiada 1.° primaria',
                'promotion_mode' => 'direct_promotion',
                'promotion_area_count' => null,
                'min_expected_level' => 'A',
                'minimum_level_for_remaining_competencies' => null,
                'permanence_mode' => 'none',
                'permanence_area_count' => null,
                'requires_recovery_for_c' => false,
                'allows_guided_promotion' => true,
                'notes' => 'Regla base para inicio de ciclo en primaria.',
            ],
            [
                'education_level' => 'primaria',
                'grade_number' => 2,
                'rule_name' => 'Cierre de ciclo primaria (2.°)',
                'promotion_mode' => 'aad_half_in_n_areas_rest_b',
                'promotion_area_count' => 4,
                'min_expected_level' => 'A',
                'minimum_level_for_remaining_competencies' => 'B',
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'A/AD en la mitad o más de competencias de cuatro áreas o talleres y B en las demás.',
            ],
            [
                'education_level' => 'primaria',
                'grade_number' => 3,
                'rule_name' => 'Promoción regular primaria (3.°)',
                'promotion_mode' => 'minimum_b_half_all_competencies',
                'promotion_area_count' => null,
                'min_expected_level' => 'B',
                'minimum_level_for_remaining_competencies' => null,
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'Como mínimo B en la mitad o más de competencias asociadas a todas las áreas.',
            ],
            [
                'education_level' => 'primaria',
                'grade_number' => 4,
                'rule_name' => 'Cierre de ciclo primaria (4.°)',
                'promotion_mode' => 'aad_half_in_n_areas_rest_b',
                'promotion_area_count' => 4,
                'min_expected_level' => 'A',
                'minimum_level_for_remaining_competencies' => 'B',
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'A/AD en la mitad o más de competencias de cuatro áreas o talleres y B en las demás.',
            ],
            [
                'education_level' => 'primaria',
                'grade_number' => 5,
                'rule_name' => 'Promoción regular primaria (5.°)',
                'promotion_mode' => 'minimum_b_half_all_competencies',
                'promotion_area_count' => null,
                'min_expected_level' => 'B',
                'minimum_level_for_remaining_competencies' => null,
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'Como mínimo B en la mitad o más de competencias asociadas a todas las áreas.',
            ],
            [
                'education_level' => 'primaria',
                'grade_number' => 6,
                'rule_name' => 'Cierre de ciclo primaria (6.°)',
                'promotion_mode' => 'aad_half_in_n_areas_rest_b',
                'promotion_area_count' => 4,
                'min_expected_level' => 'A',
                'minimum_level_for_remaining_competencies' => 'B',
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'A/AD en la mitad o más de competencias de cuatro áreas o talleres y B en las demás.',
            ],
            [
                'education_level' => 'secundaria',
                'grade_number' => 1,
                'rule_name' => 'Promoción regular secundaria (1.°)',
                'promotion_mode' => 'minimum_b_half_all_competencies',
                'promotion_area_count' => null,
                'min_expected_level' => 'B',
                'minimum_level_for_remaining_competencies' => null,
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'Como mínimo B en la mitad o más de competencias asociadas a todas las áreas o talleres.',
            ],
            [
                'education_level' => 'secundaria',
                'grade_number' => 2,
                'rule_name' => 'Cierre de ciclo secundaria (2.°)',
                'promotion_mode' => 'aad_half_in_n_areas_rest_b',
                'promotion_area_count' => 3,
                'min_expected_level' => 'A',
                'minimum_level_for_remaining_competencies' => 'B',
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'A/AD en la mitad o más de competencias de tres áreas o talleres y B en las demás.',
            ],
            [
                'education_level' => 'secundaria',
                'grade_number' => 3,
                'rule_name' => 'Promoción regular secundaria (3.°)',
                'promotion_mode' => 'minimum_b_half_all_competencies',
                'promotion_area_count' => null,
                'min_expected_level' => 'B',
                'minimum_level_for_remaining_competencies' => null,
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'Como mínimo B en la mitad o más de competencias asociadas a todas las áreas o talleres.',
            ],
            [
                'education_level' => 'secundaria',
                'grade_number' => 4,
                'rule_name' => 'Promoción regular secundaria (4.°)',
                'promotion_mode' => 'minimum_b_half_all_competencies',
                'promotion_area_count' => null,
                'min_expected_level' => 'B',
                'minimum_level_for_remaining_competencies' => null,
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'Como mínimo B en la mitad o más de competencias asociadas a todas las áreas o talleres.',
            ],
            [
                'education_level' => 'secundaria',
                'grade_number' => 5,
                'rule_name' => 'Cierre de ciclo secundaria (5.°)',
                'promotion_mode' => 'aad_half_in_n_areas_rest_b',
                'promotion_area_count' => 3,
                'min_expected_level' => 'A',
                'minimum_level_for_remaining_competencies' => 'B',
                'permanence_mode' => 'c_more_than_half_in_n_areas',
                'permanence_area_count' => 4,
                'requires_recovery_for_c' => true,
                'allows_guided_promotion' => false,
                'notes' => 'A/AD en la mitad o más de competencias de tres áreas o talleres y B en las demás.',
            ],
        ];

        foreach ($rules as $rule) {
            PromotionRule::query()->updateOrCreate(
                [
                    'education_level' => $rule['education_level'],
                    'grade_number' => $rule['grade_number'],
                ],
                array_merge($rule, ['active' => true])
            );
        }
    }
}
